name: Deploy Image Optimizer

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # Verify AWS Login
      - name: Verify AWS Login
        run: aws sts get-caller-identity

      # Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Check Terraform Formatting
      - name: Terraform Format Check
        run: terraform fmt -check

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Validate Terraform
      - name: Terraform Validate
        run: terraform validate

      # Generate Terraform Plan
      - name: Terraform Plan
        run: terraform plan

      # Sync Frontend to S3
      - name: Upload Frontend to S3
        run: |
          aws s3 sync frontend/ s3://img-processor-frontend-ap-south-1 --delete

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
          --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
          --paths "/*"

      # Verify Upload
      - name: Verify S3 Upload
        run: |
          aws s3 ls s3://img-processor-frontend-ap-south-1


              # Package Image Processor Lambda
      - name: Package Image Processor Lambda
        run: |
          cd lambda_src
          zip -r ../image_processor.zip .

      # Deploy Image Processor Lambda
      - name: Deploy Image Processor Lambda
        run: |
          aws lambda update-function-code \
            --function-name img-processor-image-processor \
            --zip-file fileb://image_processor.zip

      # Package Download Lambda
      - name: Package Download Lambda
        run: |
          cd download_lambda
          zip -r ../download_lambda.zip .

      # Deploy Download Lambda
      - name: Deploy Download Lambda
        run: |
          aws lambda update-function-code \
            --function-name img-processor-download-lambda \
            --zip-file fileb://download_lambda.zip

      # Package Image Processor Lambda
      - name: Package Image Processor Lambda
        run: |
          cd lambda_src
           zip -r ../image-processor.zip .

      # Deploy Image Processor Lambda
      - name: Deploy Image Processor Lambda
        run: |
          aws lambda update-function-code \
          --function-name img-processor-image-processor \
          --zip-file fileb://image-processor.zip

        # Package Download Lambda
      - name: Package Download Lambda
        run: |
          cd download_lambda
          zip -r ../download-lambda.zip .

      # Deploy Download Lambda
      - name: Deploy Download Lambda
        run: |
          aws lambda update-function-code \
          --function-name img-processor-download-lambda \
          --zip-file fileb://download-lambda.zip
